import { Inter } from 'next/font/google'
import './globals.css'
import Navegacion from './assets/components/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <a class="scroll-to-top" href="#">↑</a>
      <Navegacion></Navegacion>
        {children}
        <script src="../app/assets/scripts/btn-bajar.js"></script>
      </body>
    </html>
  )
}
